/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Employee_leave_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class LeaveCal extends javax.swing.JFrame {

    /**
     * Creates new form LeaveCal
     */
    public LeaveCal() {
        initComponents();
        LoadEmpno();
        Loadleave();
    }
    
    int Casual = 0;
    int Annual = 0;
    int Medical = 0;
        
    Connection con;
    PreparedStatement pst;
    PreparedStatement pst1;
    PreparedStatement pst2;
    
     public void Connection()
     {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/els","root","HM1975@skull");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EmployeeLeave.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeLeave.class.getName()).log(Level.SEVERE, null, ex);
        }
         
     }
    
    public void LoadEmpno()
    {
        Connection();
        
        try {
           pst = con.prepareStatement("select * from registration");
            ResultSet rs = (ResultSet) pst.executeQuery();
            TxtNo.removeAllItems();
            
            
            while(rs.next())
            {
              
                TxtNo.addItem(rs.getString("Empno"));
            
            }
                    
                    
                    
        } catch (SQLException ex) {
            Logger.getLogger(LeaveCal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    
    public void Loadleave()
    {
        Connection();
        
        
        
        String Empno = TxtNo.getSelectedItem().toString();
        
        try {
            pst = con.prepareStatement("select * from leaveform where Empno = ?");
            pst.setString(1, Empno);
            ResultSet rs2 = pst.executeQuery();
            
            if(rs2.next() == false)
            {
               JOptionPane.showMessageDialog(this,"Leave Information Error");
            }
            else
            {
              Casual = rs2.getInt("Casual");
              Annual = rs2.getInt("Annual");
              Medical = rs2.getInt("Medical");
            
            
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(LeaveCal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtNo = new javax.swing.JComboBox<>();
        TxtName = new javax.swing.JTextField();
        TxtCategory = new javax.swing.JTextField();
        TxtDay = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rCasual = new javax.swing.JRadioButton();
        rAnnual = new javax.swing.JRadioButton();
        rMedical = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 125));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "                 EMPLOYEE INFORMATION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 24), new java.awt.Color(51, 0, 0))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("EMPLOYEE No.");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 120, 150, 45));

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("NAME");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 250, 150, 45));

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 51));
        jLabel3.setText("CATEGORY");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 384, 150, 45));

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setText("DAYS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 150, 45));

        TxtNo.setBackground(new java.awt.Color(204, 204, 204));
        TxtNo.setFont(new java.awt.Font("Impact", 1, 18)); // NOI18N
        TxtNo.setForeground(new java.awt.Color(51, 51, 51));
        TxtNo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TxtNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNoActionPerformed(evt);
            }
        });
        jPanel1.add(TxtNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 116, 200, 45));

        TxtName.setBackground(new java.awt.Color(204, 204, 204));
        TxtName.setFont(new java.awt.Font("Impact", 1, 18)); // NOI18N
        TxtName.setForeground(new java.awt.Color(51, 51, 51));
        TxtName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(TxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 250, 200, 45));

        TxtCategory.setBackground(new java.awt.Color(204, 204, 204));
        TxtCategory.setFont(new java.awt.Font("Impact", 1, 18)); // NOI18N
        TxtCategory.setForeground(new java.awt.Color(51, 51, 51));
        TxtCategory.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(TxtCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 380, 200, 45));

        TxtDay.setFont(new java.awt.Font("Impact", 1, 18)); // NOI18N
        TxtDay.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(TxtDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, 120, 45));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Employee_leave_system/BKG 31.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 600));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "LEAVE INFO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 24), new java.awt.Color(51, 0, 51))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rCasual.setBackground(new java.awt.Color(204, 204, 204));
        rCasual.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        rCasual.setForeground(new java.awt.Color(51, 51, 51));
        rCasual.setText("CASUAL");
        rCasual.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 102)));
        rCasual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rCasualActionPerformed(evt);
            }
        });
        jPanel2.add(rCasual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 200, 55));

        rAnnual.setBackground(new java.awt.Color(204, 204, 204));
        rAnnual.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        rAnnual.setForeground(new java.awt.Color(51, 51, 51));
        rAnnual.setText("ANNUAL");
        rAnnual.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 102)));
        jPanel2.add(rAnnual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 200, 55));

        rMedical.setBackground(new java.awt.Color(204, 204, 204));
        rMedical.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        rMedical.setForeground(new java.awt.Color(51, 51, 51));
        rMedical.setText("MEDICAL");
        rMedical.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 102)));
        jPanel2.add(rMedical, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 200, 55));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Employee_leave_system/BKG 3.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 370, 610));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Jokerman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Employee_leave_system/ICON Apply 5.png"))); // NOI18N
        jButton1.setText("OK");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Jokerman", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Employee_leave_system/ICON Cancel 1.png"))); // NOI18N
        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(352, 352, 352)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rCasualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rCasualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rCasualActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         Loadleave();
        int bleave = 0;
        
        String Empno = TxtNo.getSelectedItem().toString();
        
        int Days = Integer.parseInt(TxtDay.getValue().toString());
        
        if(rCasual.isSelected() == true)
        {
            bleave = Casual - Days;
            if(bleave<0)
            {
                 JOptionPane.showMessageDialog(this,"You Have a Casual Leave" + Casual);
            }
             else
            {
                try {
                    pst = con.prepareStatement("update leaveform set Casual = ? where Empno = ?");
                    pst.setInt(1, bleave);
                    pst.setString(2, Empno);
                    pst.executeUpdate();
                   JOptionPane.showMessageDialog(this,"Your Casual Leave Updated");
                    
                    
                } catch (SQLException ex) {
                    Logger.getLogger(LeaveCal.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        
        }
        
        else if(rAnnual.isSelected() == true)
        {
              bleave = Annual - Days;
            if(bleave<0)
            {
                 JOptionPane.showMessageDialog(this,"You Have a Annual Leave" + Annual);
            }
             else
            {
                try {
                    pst1 = con.prepareStatement("update leaveform set Annual = ? where Empno = ?");
                    pst1.setInt(1, bleave);
                    pst1.setString(2, Empno);
                    pst1.executeUpdate();
                   JOptionPane.showMessageDialog(this,"Your Annual Leave Updated");
                    
                    
                } catch (SQLException ex) {
                    Logger.getLogger(LeaveCal.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            
        }
         else if(rMedical.isSelected() == true)
        {
              bleave = Medical - Days;
            if(bleave<0)
            {
                 JOptionPane.showMessageDialog(this,"You Have a Medical Leave" + Medical);
            }
             else
            {
                try {
                    pst2 = con.prepareStatement("update leaveform set Medical = ? where Empno = ?");
                    pst2.setInt(1, bleave);
                    pst2.setString(2, Empno);
                    pst2.executeUpdate();
                   JOptionPane.showMessageDialog(this,"Your Medical Leave Updated");
                    
                    
                } catch (SQLException ex) {
                    Logger.getLogger(LeaveCal.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            
        }
        
        else
         {
            JOptionPane.showMessageDialog(this,"Something Wrong");
         }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TxtNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNoActionPerformed
        // TODO add your handling code here:
        String Empno = TxtNo.getSelectedItem().toString();
        
        Connection();
        
        
        try {
            pst = con.prepareStatement("select * from registration where Empno = ?");
            pst.setString(1, Empno);
            ResultSet rs1 = pst.executeQuery();
            
            if(rs1.next() == false)
            {
                JOptionPane.showMessageDialog(this,"Emp no error");
            }
            else
            {
                String NAME = rs1.getString("EmpName");
                
                TxtName.setText(NAME.trim());
                
                String CATEGORY = rs1.getString("Category");
                
                TxtCategory.setText(CATEGORY.trim());
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(LeaveCal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TxtNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeaveCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeaveCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeaveCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeaveCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LeaveCal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtCategory;
    private javax.swing.JSpinner TxtDay;
    private javax.swing.JTextField TxtName;
    private javax.swing.JComboBox<String> TxtNo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rAnnual;
    private javax.swing.JRadioButton rCasual;
    private javax.swing.JRadioButton rMedical;
    // End of variables declaration//GEN-END:variables
}
